import "./globals.css";
import { Inter } from "next/font/google";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My Next.js App",
  description: "Generated by create-next-app",
  generator: "Next.js",
  manifest: "/manifest.json",
  keywords: ["nextjs"],
  authors: [
    {
      name: "pawan suthar",
      url: "https://example.com/your-name",
    },
  ],

  icons: [
    { rel: "apple-touch-icon", url: "icons/images-512.png" },
    { rel: "icon", url: "icons/images-512.png" },
  ],
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  minimumScale: 1,
  shrinkToFit: false,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <meta name="theme-color" content="#ffffff" />
      <link rel="manifest" href="/manifest.json" />
      <link rel="icon" href="icons/images-512.png" />
      <link rel="apple-touch-icon" href="icons/images-512.png" />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
